// Embeds the report fonts (Poppins + Noto Naskh Arabic) as base64 @font-face rules for PDF rendering,
// where the headless browser has no network access. Run: node scripts/embed-fonts.mjs
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = "src/lib/report/fonts";
const faces = readdirSync(dir).filter((f) => f.endsWith(".woff2")).sort().map((f) => {
  const [fam, weight] = f.replace(".woff2", "").split("-");
  const family = fam === "NotoNaskhArabic" ? "Noto Naskh Arabic" : fam;
  const range = family === "Noto Naskh Arabic" ? "100 900" : weight;
  const b64 = readFileSync(join(dir, f)).toString("base64");
  return `@font-face{font-family:'${family}';font-style:normal;font-weight:${range};font-display:block;src:url(data:font/woff2;base64,${b64}) format('woff2');}`;
});
writeFileSync("src/lib/report/fonts.generated.ts", `// Generated by scripts/embed-fonts.mjs — do not edit.\nexport const REPORT_FONT_CSS = ${JSON.stringify(faces.join("\n"))};\n`);
console.log(`embedded ${faces.length} font faces`);
